version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
  pre_build:
    commands:
      - echo "Install dependencies ..."
      - npm install
  build:
    commands:
      - echo "Building ..."
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build

cache:
  paths:
    - "node_modules/**/*"
