version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
  pre_build:
    commands:
      - echo "Install dependencies ..."
      - npm install
  build:
    commands:
      - echo "Building ..."
      - npm run build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR; bash deploy.sh

artifacts:
  files:
    - "build/**/*"
  discard-paths: no

cache:
  paths:
    - "node_modules/**/*"
